Neos:
  GoogleAnalytics:
    authentication:
      applicationName: 'Neos GA'
      clientId: '4730774009-h57rl51jmjbrljt2mii1ebn74a8hsrr3.apps.googleusercontent.com'
      clientSecret: '%env:GA_SECRET%'
      developerKey: '%env:GA_DEVKEY%'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp.gmail.com'
        port: '465'
        encryption: 'ssl'
        username: 'no-reply@psmb.ru'
        password: '%env:PSMB_SMTP_PASS%'
