version: "3.4"
services:
  redis:
    image: redis:3.2
  es:
    image: nikdro/elasticsearch-neos:2.4
    volumes:
      - es-data:/usr/share/elasticsearch/data 
  db:
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
  web:
    labels:
      - "neos"
    volumes:
      - /data/www/Web/_Resources
    image: dimaip/psmbdistr:latest
    hostname: 'psmbru'
    networks:
      - default
      - main
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PSMB_SMTP_PASS
      - GA_SECRET
      - GA_DEVKEY
      - PSMB_CAPTCHA_SECRET
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"
        - "traefik.docker.network=main"
        - "traefik.frontend.rule=Host:psmb.ru,dev.psmb.ru,www.psmb.ru,next.psmb.ru,en.psmb.ru,festival.psmb.ru,dev.festival.psmb.ru,server.psmb.ru"
    ports:
      - '80'
    depends_on:
      - db
      - redis
      - es
volumes:
  db-data:
  es-data:
secrets:
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  PSMB_SMTP_PASS:
    external: true
  GA_SECRET:
    external: true
  GA_DEVKEY:
    external: true
  PSMB_CAPTCHA_SECRET:
    external: true
networks:
  main:
    external:
      name: main
