version: "3.4"
services:
    redis:
        image: redis:3.2
    db:
        image: mariadb:10.3
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: db
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
volumes:
    db-data:
networks:
    main:
        external:
            name: main
