Ttree:
  ContentRepositoryImporter:
    sources:
      default:
        host: db
        driver: pdo_mysql
        dbname: db
        user: admin
        password: pass
        charset: UTF8
    presets:
      'base':
        'category':
          label: 'Import Categories'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'categories'
            siteNodePath: '/sites/site'
        'page':
          label: 'Import Pages as Categories'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\PageDataProvider'
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'pages'
            siteNodePath: '/sites/site'
        'news':
          label: 'Import News'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsImporter'
          importerOptions:
            targetNode: 'news'
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsPageRelation':
          label: 'Import relations between News and parent page'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsPageRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsCategoryRelation':
          label: 'Import relations between News and categories'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsCategoryRelationDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsCategoryRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsRelation':
          label: 'Import relations between News items'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsRelationDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsFiles':
          label: 'Import news files'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsFileDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsFileImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsContent':
          label: 'Import news content'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsContentDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsContentImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
