Ttree:
  ContentRepositoryImporter:
    sources:
      default:
        host: db
        driver: pdo_mysql
        dbname: db
        user: admin
        password: pass
        charset: UTF8
    presets:
      'ground':
        'conferences':
          label: 'Import Conferences'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          dataProviderOptions:
            startingPoint: 4
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'projects/conferences'
            siteNodePath: '/sites/site'
        'tagsPeople':
          label: 'Import People'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          dataProviderOptions:
            startingPoint: 2
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'tags/people'
            siteNodePath: '/sites/site'
        'tagsMovements':
          label: 'Import Movements'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          dataProviderOptions:
            startingPoint: 14
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'tags/movements'
            siteNodePath: '/sites/site'
        'exhibitions':
          label: 'Import Exhibitions'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          dataProviderOptions:
            startingPoint: 20
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'projects/exhibitions'
            siteNodePath: '/sites/site'
        'collections':
          label: 'Import Themes'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\CategoryDataProvider'
          dataProviderOptions:
            startingPoint: 91
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'collections'
            flatten: true
            siteNodePath: '/sites/site'
        'page':
          label: 'Import Sections'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\PageDataProvider'
          dataProviderOptions:
            startingPoint: 111
          importerClassName: 'Psmb\PsmbImport\CategoryImporter'
          importerOptions:
            targetNode: 'sections'
            siteNodePath: '/sites/site'
      'base':
        'news':
          label: 'Import News'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsImporter'
          importerOptions:
            targetNode: 'a'
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsPageRelation':
          label: 'Import relations between News and parent page'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsPageRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsCategoryRelation':
          label: 'Import relations between News and categories'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsCategoryRelationDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsCategoryRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsRelation':
          label: 'Import relations between News items'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsRelationDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsRelationImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsFiles':
          label: 'Import news files'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsFileDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsFileImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'newsContent':
          label: 'Import news content'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\NewsContentDataProvider'
          importerClassName: 'Psmb\PsmbImport\NewsContentImporter'
          importerOptions:
            siteNodePath: '/sites/site'
          batchSize: 100
        'blogs':
          label: 'Import blogs'
          dataProviderClassName: 'Psmb\PsmbImport\DataProvider\BlogsDataProvider'
          importerClassName: 'Psmb\PsmbImport\BlogsImporter'
          importerOptions:
            siteNodePath: '/sites/site'
            targetNode: 'blogs'
          batchSize: 100
