Ttree:
  ContentRepositoryImporter:
    sources:
      default:
        host: db
        driver: pdo_mysql
        dbname: db
        user: admin
        password: pass
        charset: UTF8
    presets:
      "base":
        parts:
          "sermons":
            label: "Import Sermons"
            dataProviderClassName: 'Psmb\PsmbImport\DataProvider\SermonDataProvider'
            importerClassName: 'Psmb\PsmbImport\SermonImporter'
            importerOptions:
              targetNode: "s"
              siteNodePath: "/sites/site"
            batchSize: 100
      "saints":
        parts:
          "saints":
            label: "Import Saints"
            dataProviderClassName: 'Psmb\PsmbImport\DataProvider\SaintDataProvider'
            importerClassName: 'Psmb\PsmbImport\SaintImporter'
            importerOptions:
              targetNode: "sv"
              siteNodePath: "/sites/site"
            batchSize: 100
