-
  name: 'Psmb.GoogleFormsCaptcha'
  uriPattern: 'form-captcha'
  defaults:
    '@package':    'Psmb.GoogleFormsCaptcha'
    '@controller': 'Proxy'
    '@action':     'submit'
    '@format':     'html'
  appendExceedingArguments: TRUE
