TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Site': TRUE
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
          presets:
            default:
              baseNodeType: 'TYPO3.Neos:Document,!Sfi.Site:News'
  # TYPO3CR:
  #   contentDimensions:
  #     'language':
  #       default: 'ru'
  #       defaultPreset: 'ru'
  #       label: 'Language'
  #       icon: 'icon-language'
  #       presets:
  #         'ru':
  #           label: 'Russian'
  #           values: ['ru']
  #           uriSegment: ''
  #         'en':
  #           label: 'English'
  #           values: ['en']
  #           uriSegment: 'en'
