Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      driver:
        version: 2.x
    clients:
      default:
        -
          host: es
          port: 9200
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen'
Psmb:
  GoogleFormsCaptcha:
    forms:
      contactUs: '1MAsEybLT5iHkaYgn-Y2kLjZTilZG2ayPGZLR_8oV7NA'
  Newsletter:
    globalSettings:
      senderAddress: no-reply@psmb.ru
      senderName: PSMB.ru
    subscriptions:
      -
        identifier: instant_ru
        renderer: 'Sfi.Site:InstantMail'
        sendFromUiNodeType: 'Sfi.Site:News'
        label: 'Мгновенное уведомление'
        description: 'Полные версии материалов как только они опубликованы'
        interval: PT1H
        senderName: 'Преображенское братство'
        dimensions:
          language:
            - ru
      -
        identifier: digest_ru
        renderer: 'Sfi.Site:DigestMail'
        label: 'Еженедельный дайджест'
        description: 'Письмо с лучшими публикациями за неделю'
        interval: P1W
        senderName: 'Преображенское братство'
        dimensions:
          language:
            - ru
      -
        identifier: instant_en
        renderer: 'Sfi.Site:InstantMail'
        sendFromUiNodeType: 'Sfi.Site:News'
        label: 'Instant Notification'
        description: 'Recevie full versions of articles as they are published'
        interval: PT1H
        senderName: 'Transfiguration Brotherhood'
        dimensions:
          language:
            - en
      -
        identifier: digest_en
        renderer: 'Sfi.Site:DigestMail'
        label: 'Monthly Digest'
        description: 'Receive newsletter by Sofia Androsenko to your inbox'
        interval: P1W
        senderName: 'Transfiguration Brotherhood'
        dimensions:
          language:
            - en
Neos:
  Flow:
    session:
      inactivityTimeout: 604800
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://psmb.ru/'
    log:
      systemLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      securityLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      sqlLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      i18nLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
          storageOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'storage/psmb/'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'target/psmb/'
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/psmb/'
  Neos:
    Ui:
      frontendConfiguration:
        'Psmb.CreateNodeButton':
          enabled: true
          position: 'into'
          type: 'Sfi.Site:News'
          referenceNodePath: '/sites/site/a'
          placeholder: 'Заголовок материала...'

    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
          presets:
            default:
              baseNodeType: 'Neos.Neos:Document,!Sfi.Site:News'
    nodeTypes:
      groups:
        festival:
          position: 110
          label: 'Фестиваль'
    eventLog:
      enabled: true
  GoogleAnalytics:
    stats:
      uniquePageviewsBySource:
        metrics: 'ga:uniquePageviews'
        dimensions: 'ga:source'
        sort: '-ga:uniquePageviews'
        max-results: 25
    fusion:
      autoInclude:
        Sfi.Site: true
  ContentRepository:
    contentDimensions:
      language:
        default: ru
        defaultPreset: ru
        label: Language
        icon: icon-language
        presets:
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
          en:
            label: English
            values:
              - en
            uriSegment: en
Yeebase:
  Graylog:
    host: '172.17.42.1'
    port: 12201
    chunksize: 'wan'
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
