#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the Flow manual for possible configuration options.    #
#                                                                        #

-
  name: 'Subscription'
  uriPattern: '<NewsletterSubroutes>'
  subRoutes:
    'NewsletterSubroutes':
      package: 'Psmb.Newsletter'



##
# Neos subroutes

-
  name: 'NeosNeos'
  uriPattern: '<NeosNeosSubroutes>'
  subRoutes:
    'NeosNeosSubroutes':
      package: 'Neos.Neos'
      variables:
        'defaultUriSuffix': '.html'
